export enum TAMAGOTCHI_RULES {
  HEALTH_MIN = 0,
  HEALTH_MAX = 100,
  HUNGER_MIN = 20,
  HUNGER_MAX = 100,
  FEED_THRESHOLD = 80,
  FATIGUE_MIN = 0,
  FATIGUE_MAX = 100,
  SLEEP_THRESHOLD = 80,
  AGE_MIN = 1,
  AGE_MAX = 99,
  POOP_THRESHOLD = 3,
}
